### ISSUE TITLE
Arena/Pokestop Namen erst beim Zoomen anzeigen

### ISSUE THREAD

**Issue by Soundz1337** [NickAtGit/PoGORadar#19]

**Comment by NickAtGit** [comment]
@SoundWreaking das ist leider ein bekanntes Problem. Liegt aber an Google Maps. Auf iOS funktioniert das so wie du es gern hättest. Wir schauen was wir tun können ;)

**Comment by SRichardDev** [comment]
Wurde in der 0.1.7 Version umgesetzt
