### ISSUE TITLE
On/Off für Pokestops/Arenen 

### ISSUE THREAD

**Issue by Soundz1337** [NickAtGit/PoGORadar#29]

**Comment by NickAtGit** [comment]
Kannst du bitte genauer erklären was du meinst @SoundWreaking ?

**Comment by Soundz1337** [comment]
@NickAtGit Damit man nur Arenen anzeigen lassen kann usw

**Comment by NickAtGit** [comment]
@SoundWreaking diese Funktion ist bereits in der App drin... Hast du sie noch nicht gefunden? (Plus auf der Karte und dann auf das Filter Symbol)
