### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by SoundWreaking** [NickAtGit/PoGORadar#5]
# Filter für **einzelne** Arenen.

Dadurch werden Arenen, für die man benachrichtigt werden möchte, von anderen Arenen getrennt die im selben Feld liegen.

# Route für Arenen/Pokestops

Google Maps Link statt Koordinaten im Arena/Pokestop Menü

# Drei Striche Menü

Ein drei Striche Menü damit Sachen wie Terms & Conditions und andere Informationen kompakt verstaut werden können. 

# Such Funktion für Arenen/Pokestops

Erklärt sich hoffentlich von selbst :)

**Comment by NickAtGit** [comment]
Hi @SoundWreaking vielen Dank für deinen Input. Ich habe deine Feature Requests in einzelne Issues ausgelagert, damit wir sie besser tracken können. Das Hamburger Menü (Drei Striche Menü) das du erwähnt hattest wird es aber so nicht mehr geben. Die "Terms and Conditions werden noch an eine andere Stelle verlagert.

Vielen Dank :)
